apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include  "my-nginx.fullname" . }}
  labels:
    {{- include "my-nginx.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ if eq .Values.environment.name "production" }} {{ .Values.environment.replicaCount }} {{ else }} {{ .Values.replicaCount }} {{ end }}
  selector:
    matchLabels:
      {{- include "my-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "my-nginx.selectorLabels" . | nindent 8 }}    
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          {{- if .Values.service.enabled }}
          ports:
            - containerPort: {{ .Values.containerPorts.http }}
          {{ end }}
